# Generated by Django 4.2.2 on 2023-06-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_todo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
