# Generated by Django 4.2.2 on 2023-06-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_todo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='image',
            field=models.FileField(default=None, null=True, upload_to='media/'),
        ),
    ]
